# Generated by Django 3.2.9 on 2022-01-19 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('CHB', 'Chabhail'), ('BDH', 'Boudha'), ('THL', 'Thali'), ('JRP', 'Jorpati'), ('CHK', 'Chakrapath'), ('GOK', 'Gokarna'), ('MUL', 'Mulpani'), ('GTH', 'Gothatar'), ('BHK', 'Bhaktapur')], max_length=3)),
                ('city', models.CharField(max_length=70)),
                ('zipcode', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
