# Generated by Django 3.2.9 on 2022-01-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('selling_price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=40)),
                ('category', models.CharField(choices=[('M', 'MOBILE'), ('L', 'Laptop'), ('TW', 'TopWear'), ('BW', 'BottomWear')], max_length=5)),
                ('image', models.ImageField(upload_to='productimg')),
            ],
        ),
    ]
