# Generated by Django 3.2.9 on 2022-02-01 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cart_orderplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
